version: "3"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - my_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: launch_app
    volumes:
      - $HOME/docker/volumes/launch_app:/var/lib/postgresql/data
  
  frontend:
    build: ./front-end
    ports:
      - 3000:3000
    networks:
      - my_network
    depends_on:
      - backend
      
  backend:
    build: ./back-end
    ports:
      - 8080:8080
    networks:
      - my_network
    environment:
      DB_CONNECTION_STRING: postgres://postgres:docker@db:5432/launch_app
      PORT: 8080
    depends_on:
      - db

networks:
  my_network:
    driver: bridge
